# Makefile for the xburst sound oss driver
#
# 24 APR 2012, <jbbi: jbbi@ingernic.cn>
#

obj-$(CONFIG_JZ4780_INTERNAL_CODEC) += jz4780_codec.o jz4780_route_conf.o
obj-$(CONFIG_JZ4775_INTERNAL_CODEC) += jz4775_codec.o jz4775_route_conf.o
obj-$(CONFIG_HDMI_JZ4780)			+= hdmi_virual_codec.o
