# Makefile for the xburst sound oss driver
#
# 24 APR 2012, <jbbi: jbbi@ingernic.cn>
#

obj-$(CONFIG_SOUND_OSS_XBURST) 	+= codecs/

obj-$(CONFIG_SOUND_I2S_JZ47XX) 	+= xb47xx_i2s.o

obj-$(CONFIG_SOUND_PCM_JZ47XX) 	+= xb47xx_pcm.o
